// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrryjhtqtlhscxqzglce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpycnlqaHRxdGxoc2N4cXpnbGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMjYxMDcsImV4cCI6MjA3NDcwMjEwN30.0WsTsqOGWpkxTKI7Hi2vB7TBhdPPHv9z4peJ3-LhE2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});